global using LibraryManagementClassLib.DataAccess;
global using LibraryManagementClassLib.Models;
global using LibraryManagementClassLib.BusinessLogic;
global using LibraryManagementConsoleUI.Helpers;
global using LibraryManagementConsoleUI.BookOperations;
